export {default as PlayingNow} from './playingNow/PlayingNow'
export {default as UpComing} from './upComing/UpComing'
export {default as TopRated} from './topRated/TopRated'
export {default as Header} from './header/Header'
export {default as Footer} from './footer/Footer'
export {default as Hero} from './hero/Hero'