export {default as PlayingNow} from './playingNow'
export {default as UpComing} from './upComing'
export {default as TopRated} from './topRated'
export {default as Header} from './header'
export {default as Footer} from './footer'
export {default as Hero} from './hero'